name: pangu
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy==2.2.6
      - netCDF4==1.7.3
      - xarray==2025.6.1
      - PyYAML==6.0.2
      - cdsapi>=0.7.7,<0.8
      - onnxruntime-gpu[cuda,cudnn]==1.22.0
      - pytest>=8,<9
